version: '3.8'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_value:/var/lib/postgresql2/data/
    env_file:
      - .env

  backend:
    image: novssk/foodgram-back:lastest
    volumes:
      - static_value:/app/back-static/
      - media_value:/app/back-media/
    depends_on:
        - db
    env_file:
        - .env
    restart: always

  frontend:
    image: novssk/foodgram-front:lastest
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/back-static/
      - media_value:/var/html/back-media/
volumes:
  static_value:
  media_value:
  db_value:
