version: '3.8'
services:

  db:
    image: postgres:14.6-alpine
    restart: always
    volumes:
      - db_value:/var/lib/postgresql2/data/
    env_file:
      - .env

  backend:
    image: novssk/food_back:latest
    restart: always
    volumes:
      - static_value:/app/back-static/
      - media_value:/app/back-media/
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    image: novssk/food_front:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - static_value:/var/html/back-static/
      - media_value:/var/html/back-media/
    depends_on:
      - frontend

volumes:
  static_value:
  media_value:
  db_value: