# Generated by Django 3.2 on 2023-04-07 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_add_constraints_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator('^#?([0-9a-fA-F]{6}|[0-9a-fA-F]{3})$', 'Значение не соответствует формату hex')], verbose_name='Цвет тега'),
        ),
    ]
