# Generated by Django 3.2 on 2023-04-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_tag_color'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['recipe'], name='recipes_fav_recipe__f749a7_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['name', 'measurement_unit'], name='recipes_ing_name_cc3717_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppingcart',
            index=models.Index(fields=['recipe'], name='recipes_sho_recipe__c474c8_idx'),
        ),
    ]
